### ISSUE TITLE
Weird issues with latest Angular and dragulaModel

### ISSUE THREAD

**Issue by axtho** [valor-software/ng2-dragula#670] opened 2017-04-23 18:40 UTC
Environment:
==============
@angular/cli: 1.0.0
node: 7.8.0
os: darwin x64
@angular/animations: 4.0.3
@angular/common: 4.0.3
@angular/compiler: 4.0.3
@angular/core: 4.0.3
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 4.0.3
@angular/http: 4.0.3
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.0.3
@angular/platform-browser-dynamic: 4.0.3
@angular/router: 4.0.3
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.3
@angular/platform-server: 4.0.3

Issue
======
Using the [dragulaModel] directive to move items between two arrays ends up with the wrong item on drop. Also, when I return the just dropped item it creates an empty container in the original list and does not sync the model (i.e. does not remove the returned item).

E.G. on the initial list i select fullName and drag it over to the left. On drop it creates a container middleName. When I return middleName, it removes the container on the left, creates an empty container on the right and does not update the model that belongs to the right side.

Code
====
```
export class SettingsComponent implements OnInit {
    personAttrSet: Array<string> = [
        'fullName',
        'firstName',
        'middleName',
        'lastName',
....
    ];
    personAttr: Array<string>;
    constructor(dragulaService: DragulaService) {
        dragulaService.dropModel.subscribe((value: any[]) => {
            this.onDropModel(value.slice(1));
        });
        dragulaService.removeModel.subscribe((value: any[]) => {
            this.onRemoveModel(value.slice(1));
        });
      }
      ngOnInit(): void {
        this.personAttr = this.personAttrSet.filter((item) => {
            return this.personAttrSelected.indexOf(item)!==0;
        });
       }
....
```
HTML
```
<md-card-content fxLayout="row" fxLayoutGap="10px">
      <fieldset class='container'
                [dragula]='"person-list-bag"'
                [dragulaModel]='personAttrSelected'
                fxFlex="50">
          <legend i18n>Selected</legend>
          <div *ngFor="let element of personAttrSelected" class="div" [innerHtml]='element'></div>
      </fieldset>
      <fieldset class='container'
                [dragula]='"person-list-bag"'
                [dragulaModel]='personAttr'
                fxFlex="50">
          <legend i18n>Available</legend>
          <div *ngFor="let element of personAttr" class="div" [innerHtml]='element'></div>
      </fieldset>
  </md-card-content>
```

**Comment by fuerst** [comment] 2017-05-06 08:20
Expericence the same issue using Angular 4.0.3.

**Comment by kstraszewski** [comment] 2017-05-15 12:49
I have the same issue on Angular 4.1.0, and Ionic-angular 3.2.1

**Comment by axtho** [comment] 2017-05-20 12:30
@cormacrelf is there anything you guys can point us to? I am not fully certain why that seems to be a problem. Is it TS? Angular? It's quite annoying not be able to work with otherwise great library.

I forked and updated the deps. The compilations seems to be fine (if it does it correctly) and the demo App runs well also.

**Comment by cormacrelf** [comment] 2017-05-20 13:43
You guys aren't certain your code works for earlier Angulars? I'm not a big dragulaModel user since all my stuff is @ngrx/store and Immutable.js based. I will have a go at reproducing, unless anyone wants to give me a minimal repro case first.

**Comment by axtho** [comment] 2017-05-20 13:58
Why does immutable prevent that usage? What do you do instead? I am using ngrx, so a similar concept. Is there another way to synchronize two divs  (as in the repeat-example)?
I could try to switch back, but there are so many dependencies on v4 now (like Material2) that I am not sure if that will that work at all.

Here is my code, if that helps:

HTML
```
<md-card>
  <md-card-title i18n>Person List</md-card-title>
  <md-card-content fxLayout="row" fxLayoutGap="10px">
      <fieldset class='container'
                [dragula]='"person-list-bag"'
                [dragulaModel]='personAttrSelected'
                fxFlex="50">
          <legend i18n>Selected</legend>
          <div *ngFor="let element of personAttrSelected" class="div" [innerHtml]='element'></div>
      </fieldset>
      <fieldset class='container'
                [dragula]='"person-list-bag"'
                [dragulaModel]='personAttr'
                fxFlex="50">
          <legend i18n>Available</legend>
          <div *ngFor="let element of personAttr" class="div" [innerHtml]='element'></div>
      </fieldset>
  </md-card-content>
    <div class='wrapper'>
        <div class='container'>
            <pre>{{personAttrSelected | json}}</pre>
        </div>
        <div class='container'>
            <pre>{{personAttr | json}}</pre>
        </div>
    </div>
```
TS
```
export class SettingsComponent implements OnInit {

    personAttrSet: Array<string> = [
        'fullName',
        'firstName',
        'middleName',
        'lastName',
        'avatar',
        'email',
        'birthday',
        'gender'
    ];
    personAttr: Array<string>;
    personAttrSelected: Array<string> = [
        'email'
    ];

    constructor(dragulaService: DragulaService) {
      dragulaService.dropModel.subscribe((value: any[]) => {
          this.onDropModel(value.slice(1));
      });
      dragulaService.removeModel.subscribe((value: any[]) => {
          this.onRemoveModel(value.slice(1));
      });
    }

    ngOnInit(): void {
        this.personAttr = this.personAttrSet.filter((item: string) => {
            return this.personAttrSelected.indexOf(item) !== 0;
        });
    }

    private onDropModel(args: any): void {
        let [el, target, source] = args;
        // console.log(el, target, source, this.personAttrSelected);
    }

    private onRemoveModel(args: any): void {
        let [el, source] = args;
        // console.log(el, source, this.personAttrSelected);
    }
}
```

**Comment by cormacrelf** [comment] 2017-05-20 14:17
@axtho dragulaModel modifies mutable arrays. I don't have any of those, they're all Immutable Lists. All modifications of lists I tend to do through redux actions. I have a service running in between my components and DragulaService to handle registration of containers, do my own domIndexOf and fire appropriate MOVE actions which end up rendering the dragged element in the target container. Essentially the same overall thing as dragulaModel, except without the two `Array.splice()` calls. Scratch that whole business about dragulaModel not being for more than one list, it's wrong.

My first guess on this one would be [de-synchronised lists of models & containers](https://github.com/valor-software/ng2-dragula/blob/master/src/components/dragula.provider.ts#L83).

**Comment by axtho** [comment] 2017-05-20 14:46
The odd thing is that on dragging/dropping the dragged element is the correct one, but the drop results in the dragged item not being in either of the lists. Instead, it used another item to move:

I moved "firstName", it removed that from the source but added another to target. Maybe some domeIndexOf issue...

<img width="405" alt="bildschirmfoto 2017-05-20 um 16 43 02" src="https://cloud.githubusercontent.com/assets/11181579/26276658/b7b8cfaa-3d7b-11e7-899d-2bf159d94f0c.png">

**Comment by axtho** [comment] 2017-05-20 14:48
What is the `ng-reflect-dragula-model` in each of the these fieldsets?

**Comment by cormacrelf** [comment] 2017-05-20 16:17
ng-reflect-* is for debugging purposes, it's stripped in prod builds. Ignore it.

I've found the problem though. domIndexOf is getting the wrong result because you have one <legend> element in each fieldset. Make a div inside the fieldset as the dragula container and it works perfectly. Translate this back into material/md-* and it'll be fine.

```html
<div class="card">
  <div class="card-title" i18n>Person List</div>
  <div class="card-content">
    <fieldset>
      <legend i18n>Selected</legend>
      <div class="container" [dragula]='"person-list-bag"' [dragulaModel]='personAttrSelected'>
        <div *ngFor="let element of personAttrSelected" class="div" [innerHtml]='element'></div>
      </div>
    </fieldset>
    <fieldset>
      <legend i18n>Available</legend>
      <div class="container" [dragula]='"person-list-bag"' [dragulaModel]='personAttr'>
        <div *ngFor="let element of personAttr" class="div" [innerHtml]='element'></div>
      </div>
    </fieldset>
  </div>
</div>
```

Closing because I presume all the others with this issue have the same problem.

**Closed by cormacrelf** 2017-05-20 16:17 UTC

**Comment by axtho** [comment] 2017-05-20 21:32
@cormacrelf that solved it. Thanks. Maybe something for the docs?

**Comment by cormacrelf** [comment] 2017-05-20 21:34
I'm pretty sure it's already there, it's just easy to forget. Will check it out.

**Comment by axtho** [comment] 2017-05-27 11:35
@cormacrelf you mentioned you are not using the modle. Do you have an example on how you do that? Thanks!
