### ISSUE TITLE
Pushed model view in wrong order in nested drag container

### ISSUE THREAD

**Issue by abdulkareemnalband** [valor-software/ng2-dragula#781] opened 2017-10-04 14:13 UTC
**browser**  :  chrome 61.0.3163.100 (Official Build) (64-bit)
**os**  :  windows 10 Enterprise version 1703 build 15063.608
**angular**  :  4.36
**dragula**  :  3.7.2
**ng2-dragula**  :  1.5.0

 # Premise

We have a top level draggable items ,  which in turn have draggable sub-items

Both main and sub items are bound to respective array , Object Structure is somewhat equivalent to
```js
{
 main:[
  {
    subitem:[{}.{},...]
  },
  {
    subitem:[{}.{},...]
  },
  .......
 ]
}
```

main template is like
```html
<div dragula="main" [dragulaModel]="main" [dragulaOptions]="mainOptions">
     <my-item *ngFor="let item of main" [item]="item"></my-item>
</div>
```

```html
<div #cont class="subitem-container" [dragula]="'subitem'+item.id" [dragulaModel]="item.subitems">
     <my-subitem *ngFor="let subitem of item.subitems" [subitem]="subitem"></my-subitem>
</div>
```

In item component `options` to dragula are provided by `dragulaService.setOptions` in `ngAfterViewInit` because `mirrorContainer` is set to `.subitem-container`  (  this could be mitigated if #776 is resolved) 

`mainOptions.move` is configured to return false when `.subitem-container` and its children are `handle`

# Issue
Reorder subitem and push new subitem into `item.subitems` ( `item.subitems.push(new subitem())`) 

New item appears in wrong order (instead of last postion)

This issue occurs only when subitems list is reordered using `dragula` drag and drop then pushing new subitem

Both `angular` and `drake` models contain subitems in correct order (i.e. newest subitem in last)
But in dom new Item appears in wrong order

**Comment by EduardoOliveira** [comment] 2017-11-21 17:05
I am experiencing a similar situation using splice to introduce items in the model

**Comment by vivekjoshi225** [comment] 2018-02-21 13:05
Same issue. Any solutions ?

**Comment by mstawick** [comment] 2018-03-28 17:31
Same here. Did you guys come up with a workaround?

**Comment by abdulkareemnalband** [comment] 2018-04-01 11:29
My work around is very hacky, so be warned
have two lists instead of one 
```
<div *ngIf="showSublist" [....other attr including dragula]>
    <my-subitem *ngFor="...."></my-subitem>
</div>
<div *ngIf="!showSublist" [....other attr including dragula]>
    <my-subitem *ngFor="...."></my-subitem>
</div>
```
on inserting item
I set `showSublist = false` and again set `showSublist = true` in `setTimeout`

This works for me but YMMV

**Comment by mstawick** [comment] 2018-04-02 13:40
Thanks for sharing.

**Comment by cormacrelf** [comment] 2018-06-21 03:13
I think this is change detection related. A ParentComponent, hosting a dragula container, has a list they pass to dragulaModel. The DragulaService, [when it receives a drop](https://github.com/valor-software/ng2-dragula/blob/master/src/components/dragula.provider.ts#L78-L101) merely modifies the array you gave it.

Under some circumstances, perhaps this included, it might be possible that ParentComponent does not have its change detection run. The NgForOf directive wouldn't receive the updated list, and wouldn't re-render. Then, it's plausible that it would convert `Array.push` into inserting a node after the previous last child, given that NgForOf operates on the elements of a list, not their parent element, so Node.appendChild wouldn't be possible.

**Comment by cormacrelf** [comment] 2018-06-21 03:14
I would want to know if it goes away if you don't set the mirror container.

**Comment by abdulkareemnalband** [comment] 2018-07-18 05:33
@cormacrelf  Yes I will try to create a stackblitz for this later today.

**Comment by cormacrelf** [comment] 2018-07-19 16:32
@abdulkareemnalband If you need a template, I made one here:

[StackBlitz template](https://stackblitz.com/edit/ng2-dragula-base?file=src/app/app.component.html)

It's part of the bug report issue template now.

**Comment by cormacrelf** [comment] 2018-07-19 17:23
So I went a head and made it. Can't reproduce the issue with an `<input>` and a `<button>` in each `my-item` (in this demo, `some.component.ts`). I'm going to close this issue now, because it doesn't seem to be on ng2-dragula's end. If you can make the blitz fail, then I can reopen.

https://stackblitz.com/edit/ng2-dragula-776?file=src%2Fapp%2Fsome.component.ts

**Closed by cormacrelf** 2018-07-19 17:23 UTC
Labels: bug, cause: dragulaModel

**Comment by cormacrelf** [comment] 2018-07-19 23:42
FWIW, still works in v2. But it may help to notice that if you don't follow the migration-v2 guide fully and don't do the new two-way binding `[(dragulaModel)]`, it behaves roughly like you describe.

https://stackblitz.com/edit/ng2-dragula-781-776-v2?file=src%2Fapp%2Fsome.component.ts

**Comment by form-hub** [comment] 2021-06-12 05:04
> FWIW，仍然适用于 v2。但注意到如果您不完全遵循迁移 v2 指南并且不执行新的双向绑定`[(dragulaModel)]`，它的行为可能会与您描述的大致相同。
> 
> https://stackblitz.com/edit/ng2-dragula-781-776-v2?file=src%2Fapp%2Fsome.component.ts

@cormacrelf  this example group[0] and group2[1] Mutual movement
