### ISSUE TITLE
ng2-dragula and ng2-select don't work together in Firefox v50.1.0

### ISSUE THREAD

**Issue by dlcooper** [valor-software/ng2-dragula#504] opened 2016-12-27 15:00 UTC
Please see attached project.  It demonstrates the problem that, in Firefox, once ng2-dragula is configured the behavior of ng2-select dropdown changes.  One must click on the whitespace around the text in the select list in order to pick an entry.

I don't know if this is a problem for ng2-dragula or ng2-select so I'm going to open an issue in each project.

[dragula-select-conflict.zip](https://github.com/valor-software/ng2-dragula/files/674275/dragula-select-conflict.zip)

**Comment by valorkin** [comment] 2017-01-18 15:53
It is interesting, I will try to get it fixed this week

**Comment by valorkin** [comment] 2017-01-18 15:59
@SergeyKuryatnick can you reproduce in chrome?

**Comment by dlcooper** [comment] 2017-01-18 16:08
I do all my development in Chrome.  It doesn't seem to be a problem.  Only firefox.


________________________________

**Comment by valorkin** [comment] 2017-01-18 16:18
Is there are any error in console?

**Comment by dlcooper** [comment] 2017-01-18 16:23
No error.  Basically there's no response at all to the click when the cursor is over the text of the drop down option.



________________________________

**Comment by dlcooper** [comment] 2017-01-27 13:27
Any luck with this one?

**Comment by dlcooper** [comment] 2017-03-13 14:33
I experienced this in Chrome today...same quiet failure, i.e. no messages on the console but I had to click on the white space around the value in the drop down to select an entry.

Any word on this bug?

**Comment by miloskovacevic** [comment] 2017-04-11 09:19
Same problem on Chrome. Ng2-select dropdown at first works but after going on page that implements ng2-dragula same dropdown only works when i click on white space next to text or image in dropdown item.

**Comment by trevex** [comment] 2017-04-21 15:32
Having a similar problem. I am using `ng2-dragula` in a component. Whenever I access the route (lazy loaded), buttons on another route stop receiving click events. If I only access the route with the buttons everything works (after resfresh). Both routes have no shared state what so ever.

**Comment by cormacrelf** [comment] 2018-07-18 14:11
This wrapper doesn’t include any event handlers. At all. That’s all upstream in Dragula.

**Comment by cormacrelf** [comment] 2018-07-27 13:21
Closing because upstream.

**Closed by cormacrelf** 2018-07-27 13:21 UTC
Labels: bug, upstream dragula
