### ISSUE TITLE
[bug report] Types definition issue

### ISSUE THREAD

**Issue by fttx** [valor-software/ng2-dragula#912] opened 2018-10-27 09:11 UTC
**Describe the bug (required)**

When i run tsc on my project i get: 
```
/node_modules/ng2-dragula/dist/MockDrake.d.ts, line: 22
            Class 'MockDrake' incorrectly implements interface 'DrakeWithModels'. Types of property 'on' are
            incompatible. Type '(event: string, callback: Function) => void' is not assignable to type '(events: string,
            callback: Function) => Drake'. Type 'void' is not assignable to type 'Drake'.

      L22:  export declare class MockDrake implements DrakeWithModels {
      L23:      containers: Element[];
```

**To Reproduce (required)**

Install the packages at the version below and run tsc

**Versions (required)**

 - "@angular/core": "5.2.11"
 - "ng2-dragula": "2.1.0"
 - "typescript": "2.6.2"
 - @types/dragula@2.1.34

If i change the line 42 of node_modules\ng2-dragula\dist\MockDrake.d.ts from
`on(event: string, callback: Function): void;`
to
`on(event: string, callback: Function): Drake;`

everything works

Also see: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15422

**Comment by chris246** [comment] 2018-10-28 15:48
Same issue here using:
* "@angular/core": "6.1.6",
* "ng2-dragula": "2.0.4",
* "typescript": "2.9.2" 
* @types/dragula@2.1.33

Error when building:
`ERROR in node_modules/ng2-dragula/dist/MockDrake.d.ts(41,5): error TS2416: Property 'on' in type 'MockDrake' is not assignable to the same property in base type 'DrakeWithModels'.
  Type '(event: string, callback: Function) => void' is not assignable to type '(events: string, callback: Function) => Drake'.
    Type 'void' is not assignable to type 'Drake'.`

**Comment by Mohendran** [comment] 2018-10-28 19:08
@fttx 
Same Issue here...

However, It worked for me when I used @types/dragula@2.1.33

@chris246 check your package-lock.json file for the version number.

**Comment by daiyis** [comment] 2018-10-29 02:54
same issue. Manually add "@types/dragula": "2.1.33" into package.json fixed on my side.

**Comment by joshstrohminger** [comment] 2018-10-29 03:07
Not sure if you mean to add it as a dependency or a [resolution ](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) but the resolution fixed it for me.
```json
"resolutions": {
    "@types/dragula": "2.1.33"
}
```

**Comment by urdenko** [comment] 2018-10-29 11:30
This problem is very relevant now. Please fix it as soon as possible.

**Comment by lisa13** [comment] 2018-10-29 12:04
I am using angular 6 so I can't exactly go back to an older version of angular just for the sake of using dragula. 
One solution that worked for us was to:

import { Drake } from 'dragula';
in the node_modules\ng2-dragula\dist\MockDrake.d.ts file, 

then chenge:
on(event: string, callback: Function): void;
to
on(event: string, callback: Function): Drake;

**Comment by wendelstam** [comment] 2018-10-29 12:37
I have made a change in a branch, I will test it later today and if it works I will submit a PR
(https://github.com/wendelstam/ng2-dragula/blob/master/modules/ng2-dragula/src/MockDrake.ts)

**Comment by nadeemgori2** [comment] 2018-10-29 12:56
@wendelstam 
here return type should be void
  on(event: string, callback: Function): any {
  }

**Comment by igoriok3001** [comment] 2018-10-29 13:16
Adding ""@types/dragula": "2.1.33"" to dependencies in package.json have fixed this issue in our solution.

**Comment by chris246** [comment] 2018-10-29 13:20
Adding the resolution from https://github.com/valor-software/ng2-dragula/issues/912#issuecomment-433775326 worked for me

**Comment by Poojal123** [comment] 2018-10-29 13:31
@wendelstam still same issue. after your commit.

**Comment by vesrah** [comment] 2018-10-29 19:20
I needed to get this working sooner than later so I ended up forking and opening a PR.

**Comment by mnolan98-usf** [comment] 2018-10-31 20:34
How soon will this be fixed?  If you're not going to pin to a very specific version you need to really make sure you aren't breaking others.  I'm days away from a production deployment and need to make a small configuration change that I can no longer get a build working for due to this issue.

**Comment by cormacrelf** [comment] 2018-11-01 10:43
Guys. Patch released. But please read.

The reason many libs use semver for secondary dependencies is twofold: so that other dependents can be satisfied using the same resolved version, and so that we don't need to run a patch release every time a dep changes. Library authors push the responsibility for reproducible builds onto consumers. That's you. If you don't do this job, you will get problems. This is how it works for almost every single NPM package.

**Yarn and package-lock.json were invented to do the job for you. Every JS developer needs to be using one of them** because trusting semver for your own production releases is plain irresponsible.

I can't even reproduce this without implementing the workaround(s) in reverse. Please everyone check that you have that and it's working, and that you aren't doing `rm yarn.lock` just to get upgrades (use `yarn upgrade-interactive` instead).

If you do, we'll all be less frustrated by issues like this. I know the comments here represent a small proportion of total downloads, so looks like everyone else is OK.

Big up to @rkgoswami for suggesting we open an issue on bevacqua/dragula though. Hilarious.

**Closed** 2018-11-01 10:42 UTC

**Comment by fttx** [comment] 2018-11-01 10:57
There is so much information on npm that it's easy to miss the important things and don't see the big picture, thanks

**Comment by katkoorishruthi** [comment] 2018-11-01 11:01
Hi,
I am not able to fix the issue after updating to 2.1.33
can you suggest me plz!!

**Comment by cormacrelf** [comment] 2018-11-01 11:04
# Oh, and you guys are going to have to remove the workarounds you’ve done.

**Comment by mohamedbrahimi** [comment] 2018-11-21 16:52
try to change in /node_modules/ng2-dragula/dist/MockDrake.d.ts line 41 
on(event: string, callback: Function): void;
to
on(event: string, callback: Function): any;
that worked for me

**Comment by desoga10** [comment] 2018-12-23 13:35
> 
> 
> try to change in /node_modules/ng2-dragula/dist/MockDrake.d.ts line 41
> on(event: string, callback: Function): void;
> to
> on(event: string, callback: Function): any;
> that worked for me

This also worked for me now. After almost two days of no progress. Thanks.
