### ISSUE TITLE
Radio button with dynamic values inside ngfor outside dragula container doent work 

### ISSUE THREAD

**Issue by suneethar** [valor-software/ng2-dragula#830] opened 2018-02-14 16:10 UTC
I am using angular5 with ng-dragula .Radio button with dynamic values inside ngfor doent work. Radio button is not getting selected but If I comments dragula container names the nradio button select works fine but with dragula radio button is not getting selected

**Comment by cormacrelf** [comment] 2018-06-20 08:08
Dupe of #832

**Closed by cormacrelf** 2018-06-20 08:08 UTC
