### ISSUE TITLE
"advanced" implementation/usage: one side sorting, copying and switching dragged item content/template.

### ISSUE THREAD

**Issue by Caroga** [valor-software/ng2-dragula#728] opened 2017-05-29 12:27 UTC
I've managed to get the drag and drop to work to only drop from one side to the other, but sorting is being cancelled out. I wish to be able to keep sorting on one side (target side) and not on the other side (source side).

Also, I wish to replace the HTMLElement with a different template when being dropped, and even better: while being dropped as well.

I find the documentation to be lacking clear use cases and would love to see how this could be done, and what I should be using.

This is my code so far:

``` typescript
import {Component} from "@angular/core";
import {DragulaService} from "ng2-dragula";
import {DragAndDropHelper} from "../../../helpers/DragAndDropHelper";

@Component({
    selector: 'app-segment-dropzone',
    templateUrl: './segment-dropzone.component.html',
    styleUrls: ['./segment-dropzone.component.scss']
})
export class SegmentDropzoneComponent {
    constructor(private dragulaService: DragulaService) {
        dragulaService.setOptions('elements-bag', {
            copy: true,
            copySortSource: true,
            accepts: function (el, target, source, sibling) {
                return target.id === 'elements-dropzone';
            },
        });
        dragulaService.drag.subscribe((value) => {
            this.getElementView(DragAndDropHelper.getElementIdFromDraggedItem(value[1]));
        });
    }

    public getElementView(elementId: string) {
        console.log(elementId);
    }
}
```
`target html`

``` html
<div class="row">
    <div class="col-lg-12">
        <ul [dragula]='"elements-bag"' id="elements-dropzone">
            <li>first item</li>
            <li>second item</li>
        </ul>
    </div>
</div>
```
`source html`

``` html
<div class="mt-list-container list-simple">
    <ul [dragula]='"elements-bag"' id="elements-list">
        <li class="mt-list-item" *ngFor="let element of elements" [attr.data-element-id]="element.id" >
            <div class="list-icon-container done">
                <i class="icon-check"></i>
            </div>
            <div class="list-datetime">{{ element.type }}</div>
            <div class="list-item-content">
                <h3 class="">{{ element.name }}</h3>
            </div>
        </li>
    </ul>
</div>
```

Goal in short: 

1). drag and drop only from the right to the left side: done, is done using accept property. 
2). Allow sorting on the left side (target side, id="elements-dropzone") only. Not on the right side! 
3). Change element template ~~while being dragged and~~ after being dropped.

Would love to see any pointers on this. Thank you very much.

**Comment by cormacrelf** [comment] 2017-05-30 15:26
Figuring out how to do your 3 things isn't really something we have the power to solve over here. For (2), I don't know, but have a look at the `bevacqua/dragula` repo's README docs. For (3) there's some discussion over at the upstream `dragula` repo about allowing custom mirror elements, but there's nothing merged yet. That's not quite your problem, but it's close. That repo is a bit stagnant at the moment, too.

I personally think the actual HTML drop part of Dragula is useless for front-end apps. Having the truth in the DOM is great if you use jQuery and the rest of your app already does that, but otherwise, it is a massive pain. Remember that `ng2-dragula` does practically nothing except register the same bag in the same drake and optionally sync DOM changes back to arrays as a leaky band-aid over the problem. Instead, dragula would be a lot better and more intuitive for many more advanced use cases if it only fired events (without moving elements around) when you dropped stuff. Any template-renderer-style JS lib like Angular or React is better off this way, it can simply handle an event, add something to the list in the right place, and render that.

As it stands, `ng2-dragula`'s model sync is one big lucky hack based on the fact that the changes `dragula` makes to the DOM are the same as the ones Angular would make if you simply modified the relevant arrays. This breaks down quickly, like in your (3) case, and is very hard to debug, with mysterious HTML elements flying all over the place when we're not used to Angular code doing that. If, for example, an element gets dropped and ends up duplicated at the destination because our destination container rendered a new one as well, `ng2-dragula` users tend to immediately blame the library and start filing bug reports.

Think about it this way: if a drag out of a container would merely call you back, you could implement `copy` yourself by copying one array element to another array. You could implement a 'trash can'/'black hole' drop zone by removing from the source list and doing nothing else. You could implement (2) by doing nothing in the callback if `sourceEl == destEl && destEl.id == '...'`. You would solve (3) by never having to deal with non-homogenous HTML elements being dropped and instead modifying the data model that renders the target container in a callback to display another item with whatever template you wanted to render there.

I'm not sure how to walk the line around where to put the callbacks. Some users have requested narrowing callbacks down from drake-level to container-level, i.e. `(dragulaDrop)="..." (dragulaAccepts)="..."` next to the `dragula` property, by dispatching drake-level events by their relevant container (which you map to a model attribute through `dragulaModel`). That feels clumsy to me though, since you'd have to split your remove-from-source-list and add-to-destination-list logic and it wouldn't work very well if you wanted to copy to some destinations but reorder/move for others, like in your case.

Alternatively, you could just follow drake-level callbacks with some extra event args. I think this is best. It keeps your drag and drop code in the one location, and if you really want to have custom behavior for specific containers that they are responsible for, you can also subscribe there and simply filter based on the lists or the elements in the callback.

It's true that `dragula` attempts to implement as much functionality as possible with boolean settings or boolean callbacks for ease of use, but looking at our GH issues, this model isn't powerful enough. Most of the more advanced issues cropping up on here would be a lot simpler if we took the truth out of the DOM. It might still be possible to build the basic-functionality booleans by having default implementations of stuff like `copy`, or at least some helper or example functions like `move(model, sourceArray, destArray, targetIndex)`. 

We would need an extra drake property to prevent actually moving elements around, which would necessarily disable a few of the other options like `copy`. But then, you could do all manner of currently-impossible or currently-super-difficult things:

* Simply render the same underlying items differently in different containers
* Conditionally copy if you're holding the ctrl key down
* Prevent duplicates in destination containers even with copy functionality by checking if something already appears in the destination list
* More generally enforce properties about lists through your `accepts` callback, like preventing someone dragging into a container where the sum of items in the container would be > a limit
* Use immutable lists and redux-style actions like `@ngrx/store` with dragulaModel
* Implement multi-selection and then drag/drop many items at once (also needs custom mirror elements)

**Comment by Caroga** [comment] 2017-06-15 14:08
Very much appreciate your response.
Really have no idea on what to do now, so we are looking into "hacking" a bit, using some sort of search and replace listener on the dropzone.
Anything I could do to stir up the conversation on the upstream ?

**Comment by cormacrelf** [comment] 2017-06-15 16:11
Your hack might turn out fairly reliable if you search and destroy rather than replace, and trigger a change detection with a new item in the array. Upstream wise, dunno. I'll probably file an issue and maybe a PR eventually, but I'm tied up working with legacy code for a while. Aside from that? Tag @bevacqua and hope for the best.

**Comment by mcblum** [comment] 2017-11-01 16:14
@Caroga did you ever figure this out? We have almost the exact same use case: there is a list of elements on the right that should be dragged on to a list on the left. They are copied to the list on the left, and once they are copied to the list on the left they can be re-ordered on the left but not dragged back to the right.

This sounds like what you are doing.

**Comment by Caroga** [comment] 2017-11-06 14:16
@mcblum Sorry for the late response.

Yes this is one part of the implementation. I've got it to work entirely, but to address your specific issue I would need to take a look at the code (currently not at the office).
I'll send it to you asap.

**Comment by immortal-88** [comment] 2017-12-04 16:30
In my case i have three columns:
1) elements-container - from where i copy items and do not allow to sort them
2) two-col-left and two-col-right - here i can sort them and drag between each other

Code for that is below:

`dragulaService.setOptions('first-bag', {
      copy: function (el, source) {
        // To copy only elements from elements-container, the two-col-left and two-col-right can still be sorted
        return source.id === 'elements-container';
      },
      copySortSource: false,
      accepts: function(el, target, source, sibling) {
        // To avoid draggin from two-col-left and two-col-right to elements-container
        return target.id !== 'elements-container';
      }
    });`

**Comment by Caroga** [comment] 2018-01-29 15:35
Hi @immortal-88,
I've been out of the office for quiet some time now (health issues) and just resumed my activities again.
Would you still like me to send you my code ?

**Comment by inv-senchuthomas** [comment] 2018-03-01 13:58
@Caroga  whether it possible to delete  multiple items from the dropzone by pressing the ctrl key and selecting the items. And if they dragged out of the area we need to ask for confirmation to delete if it confirmed multiple items need to be deleted other ways the action should be rolled back

**Comment by cormacrelf** [comment] 2018-08-12 05:55
There is an example for this now (the copy-one-way, sort other one thing). Changing templates may or may not work, but it's not something I will be spending any time on. These days you have my other library, [`angular-skyhook`](https://cormacrelf.github.io/angular-skyhook/), for cool stuff like that.

**Closed by cormacrelf** 2018-08-12 05:55 UTC

**Comment by Caroga** [comment] 2018-08-13 20:08
Thanks for the edit and for creating such library!
:+1:
