### ISSUE TITLE
ng2-dragula sometime returns null on drag and drop

### ISSUE THREAD

**Issue by tawanghar** [valor-software/ng2-dragula#760] opened 2017-08-07 15:01 UTC
I am having some issues with Ng-dragular where when you drag , some time you get a NULL value, and then it returns to a working state after some time, not sure what is wrong, here is the snapshot of the issue Here is the URL to a Screen GIF 
https://s2.postimg.org/ewewhmb21/dragular.gif

HTML:
```html
<div [dragula]='"users-list-item"' [dragulaModel]="users">
    <ng-template let-user let-last="last" ngFor [ngForOf]="users">
        <md-list-item layout-align="row" data-id={{user?.id}}>
            <span>{{user?.id}}</span>
            <span>{{user?.username}}</span>
        </md-list-item>
    </ng-template>
</div>
```

TS:
```typescript
// [bag_name, drag_item, from_container, to_container, over_item]
declare type DropArgumentType = [string, HTMLElement, HTMLElement, HTMLElement, HTMLElement];

export class UsermappingComponent {

    public constructor(
        private dragulaService: DragulaService,
    ) {

        // Drop Service
        dragulaService.drop.subscribe((value: DropArgumentType) => {
            const drop_over_item = value[4];

            // Create Object for API call
            let umData: IEditUserData = {
                position: 'BEFORE ' + drop_over_item.getAttribute('id'), // Sometimes this returns 'BEFORE null'
                username: value[1].children[0].children[3].innerHTML
            }

            this.update(umData);
            // sends new position value to API, so server can update the positioning
            // Ex.: 'BEFORE 3' which means the element was dropped before the Element with ID of 3
        });

        // Over Service
        dragulaService.over.subscribe((value: any) => {
            this.onOver(value.slice(1));
        });

        // Out Service
        dragulaService.out.subscribe((value: any) => {
            this.onOut(value.slice(1));
        });

    }

    private onDrag(args) {
        let [e] = args;
    }

    private onOver(args) {
        let [el] = args;
    }

    private onOut(args) {
        let [el] = args;
    }

    private onDrop(args: any): void {
        let [e] = args;
    }

    // Update User List
    update(data: IUserData) {
        this._usersService.editUserList(data)
            .subscribe(() => {
                this.refreshData();
            }, (error: any) => {
                console.log(error);
            });
    }

}
```

**Comment by KevinJMC** [comment] 2018-05-09 17:15
+1

**Comment by cormacrelf** [comment] 2018-06-13 07:15
Can you step through it in your browser debugger and work out what element drop_over_item is, and whether that is what you expected?

**Comment by cormacrelf** [comment] 2018-07-18 12:57
I still don’t understand what the problem is. There is too much of your own code to decipher. If you can create a StackBlitz with a minimal reproduction, then I can help. Otherwise I’ll just close the issue assuming the problem is on your end.

**Closed** 2018-07-27 13:14 UTC
